
FROM idg-repository.hcmtelecom.vn/gpa_sanpham_dev/node:1.0 as build
WORKDIR /tmp
COPY WebClient/package.json /tmp/
ENV NODE_ENV=development
RUN npm install
COPY /WebClient/ /tmp/
ENV NODE_ENV=production

# 👉 Thêm dòng này để tăng heap memory
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN npm run build

FROM idg-repository.hcmtelecom.vn/gpa_sanpham_dev/nginx:1.0
COPY --from=build /tmp/dist /usr/share/nginx/html
COPY --from=build /tmp/static /usr/share/nginx/html/static
COPY /WebClient/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
